users/urls.py
from django.urls import path

from .views import SignUpView, EditProfileView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('<int:pk>/edit/', EditProfileView.as_view(), name='edit_profile')
]

vincent/urls.py
from django.urls import path

from .views import HomePageView, PostListView, PostUpdateView, PostDetailView, PostDeleteView, PostCreateView, \
    CommentCreateView, UserProfileView

urlpatterns = [
    # home
    path('', HomePageView.as_view(), name='home'),

    # posts
    path('posts/', PostListView.as_view(), name='post_list'),
    path('posts/new/', PostCreateView.as_view(), name='post_create'),
    path('posts/<int:pk>/',
         PostDetailView.as_view(), name='post_detail'),
    path('posts/<int:pk>/edit/',
         PostUpdateView.as_view(), name='post_edit'),
    path('posts/<int:pk>/delete/',
         PostDeleteView.as_view(), name='post_delete'),
    path('posts/<int:pk>/comment/',
         CommentCreateView.as_view(), name='add_comment'),

    # users
    path('users/<int:pk>/',
         UserProfileView.as_view(), name='user')

]

vincent_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('vincent.urls')),
]

users/models.py
from django.contrib.auth.models import AbstractUser

from django.db import models
from django.urls import reverse


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)
    about = models.CharField(max_length=255, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('user', args=[str(self.id)])

vincent/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created = models.DateTimeField(editable=False)
    modified = models.DateTimeField(editable=False)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    def save(self, *args, **kwargs):
        now = timezone.now()
        if not self.id:
            self.created = now
        self.modified = now
        return super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    class Meta:
        ordering = ['-id']


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.CharField(max_length=255)
    created = models.DateTimeField(editable=False)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    def save(self, *args, **kwargs):
        now = timezone.now()
        if not self.id:
            self.created = now
        return super(Comment, self).save(*args, **kwargs)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.post.id)])

    class Meta:
        ordering = ['-created']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=150, required=True)
    about = forms.CharField(max_length=255)

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('first_name', 'last_name', 'username', 'email', 'age', 'about')


class CustomUserUpdateForm(ModelForm):
    email = forms.EmailField(required=True)
    about = forms.CharField(max_length=255, required=False)

    class Meta:
        model = CustomUser
        fields = ('email', 'age', 'about')

vincent/forms.py
from django import forms

from vincent.models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('comment',)

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from users.models import CustomUser
from .forms import CustomUserCreationForm, CustomUserUpdateForm


def can_edit_only_oneself(self):
    return self.get_object() == self.request.user


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


class EditProfileView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserUpdateForm
    template_name = 'users/profile_edit.html'
    test_func = can_edit_only_oneself

vincent/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView
from django.views.generic import TemplateView, DetailView, UpdateView, DeleteView, CreateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormView

from users.models import CustomUser
from vincent.forms import CommentForm
from .models import Post, Comment


def can_edit_only_own_posts(self):
    post = self.get_object()
    return post.author == self.request.user


class HomePageView(TemplateView):
    template_name = 'home.html'


class PostListView(ListView):
    model = Post
    template_name = 'posts/post_list.html'
    paginate_by = 6
    context_object_name = 'posts'


class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context


class CommentCreateView(SingleObjectMixin, FormView):
    model = Comment
    form_class = CommentForm
    template_name = "posts/post_detail.html"
    post_object = None

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.post_object = get_object_or_404(Post, pk=kwargs['pk'])
        comment = self.form_class(request.POST).save(commit=False)
        comment.post = self.post_object
        comment.author = request.user
        comment.save()
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('post_detail', kwargs={'pk': self.post_object.pk})


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ('title', 'body',)
    template_name = 'posts/post_edit.html'
    test_func = can_edit_only_own_posts


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'posts/post_delete.html'
    success_url = reverse_lazy('post_list')
    test_func = can_edit_only_own_posts


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'posts/post_new.html'
    fields = ('title', 'body',)

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UserProfileView(ListView):
    model = Post
    template_name = 'users/profile_detail.html'
    paginate_by = 6
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(CustomUser, id=self.kwargs['pk'])
        context['profile_user'] = user
        return context

    def get_queryset(self):
        queryset = Post.objects.filter(
            author_id=self.kwargs['pk'],
        )
        return queryset

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Vincent{% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,
initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="container">
        {% if user.is_authenticated %}
            <a class="navbar-brand display-4" href="{% url 'post_list' %}">Vincent</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="btn btn-primary" href="{% url 'post_create' %}">New post</a></li>
            </ul>
        {% else %}
            <a class="navbar-brand" href="{% url 'home' %}">Vincent</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userMenu"
                               data-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right"
                                 aria-labelledby="userMenu">
                                <a class="dropdown-item"
                                   href="{% url 'user' user.id%}">Profile</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item"
                                   href="{% url 'edit_profile' user.id%}">Edit profile</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item"
                                   href="{% url 'password_change' %}">Change password</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}">
                                    Log Out</a>
                            </div>
                        </div>
                    </li>
                </ul>
            {% else %}
                <form class="form-inline ml-auto">
                    <a href="{% url 'login' %}" class="btn btn-outline-secondary">
                        Log In</a>
                    <a href="{% url 'signup' %}" class="btn btn-primary ml-2">
                        Sign up</a>
                </form>
            {% endif %}
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}
    {% endblock content %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Vincent</h1>
        <p class="lead">A poor man's Twitter clone built with Django</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'post_list' %}"
               role="button">View all posts</a>
        </p>
    </div>
{% endblock content %}

templates/posts/_post_list_partial.html
{% if posts %}
    {% for post in posts %}
        <div class="card shadow-sm h-md-250 mb-2">
            <div class="card-header inline-flex py-1 px-3">
                    <span>
                        <a class="text-muted font-weight-bold"
                           href="{% url 'user' post.author.id %}">{{ post.author }}</a>
                    </span>
                <span>
                    <a class="text-dark" href="{% url 'post_detail' post.id %}">
                        {{ post.created }}
                    </a>
                </span>
                {% if post.modified != post.created %}
                    <span class="font-italic">
                        (edited {{ post.modified }})
                        </span>
                {% endif %}
            </div>
            <div class="card-body py-1 px-3">
                <h3 class="mb-0">
                    <a class="text-dark"
                       href="{% url 'post_detail' post.id %}">{{ post.title|truncatechars:100 }}</a>
                </h3>
                <span>{{ post.body|truncatewords:60 }}</span>
            </div>
            {% if post.comment_set.all %}
                <div class="card-footer py-1 px-3 bg-white border-top-0 text-muted">
                    <span><a class="text-dark"
                             href="{% url 'post_detail' post.id %}#comments">{{ post.comment_set.count }} comment(s)</a></span>
                </div>
            {% endif %}
        </div>
    {% endfor %}
    {% if is_paginated %}
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">&laquo;</span>
                    </li>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="page-item active">
                            <span class="page-link">{{ i }}</span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">&raquo;</span>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% else %}
    <h3>No posts</h3>
{% endif %}

templates/posts/post_delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <h2 class="display-4">Delete <a class="text-muted"
                                            href="{% url 'post_detail' post.id %}">{{ post.title }}</a></h2>
        </div>
        <div class="card-body">
            <form action="" method="post">{% csrf_token %}
                <p>Are you sure you want to delete "{{ post.title }}"?</p>
                <button class="btn btn-danger ml-2" type="submit">Confirm</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/posts/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card">
        <div class="post-entry card-header">
            {% if user == post.author %}
                <p class="font-weight-bold mb-0">
                    <a href="{% url 'post_edit' post.pk %}">Edit</a> |
                    <a href="{% url 'post_delete' post.pk %}">Delete</a>
                </p>
            {% endif %}
            <h2 class="display-4">{{ post.title }}</h2>
            <p>
                <span class="font-weight-bold"><a class="text-muted"
                                                  href="{% url 'user' post.author.id %}">{{ post.author }}</a></span>
                <span>{{ post.created }}</span>
                {% if post.modified != post.created %}
                    <span class="font-italic">(edited {{ post.modified }})</span>
                {% endif %}
            </p>
        </div>
        <div class="card-body">
            <p>{{ post.body }}</p>
        </div>
        <div class="card-footer" id="comments">
            {% if user.is_authenticated %}
                <div class="mb-3">
                    <form action="{% url 'add_comment' pk=post.pk %}" method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-primary ml-2" type="submit">Add comment</button>
                    </form>
                </div>
            {% endif %}
            {% if post.comment_set.all %}
                {% for comment in post.comment_set.all %}
                    <p class="mb-0">
                        <span class="font-weight-bold text-muted">
                            <a href="{% url 'user' comment.author.id %}">{{ comment.author }}</a>
                        </span>
                        <span>{{ comment.created }}</span>
                    </p>
                    <p>
                        <span>{{ comment }}</span>
                    </p>
                {% endfor %}
            {% else %}
                <p>No comments yet</p>
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/posts/post_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h2 class="display-4">Edit <a class="text-muted" href="{% url 'post_detail' post.id%}">{{ post.title }}</a></h2>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary ml-2" type="submit">Update</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/posts/post_list.html
{% extends 'base.html' %}

{% block title %}Posts{% endblock title %}
{% block content %}
    <div class="col-12">
        <h2 class="display-4 mb-3">All posts</h2>
        {% include 'posts/_post_list_partial.html' %}
    </div>
{% endblock content %}

templates/posts/post_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>New post</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>
{% endblock content %}

templates/users/_user_profile_partial.html
<div class="card">
    <div class="card-header">
        <h3 class="display-4 text-center">{{ profile_user.username }}</h3>
    </div>
    <div class="card-body">
        <p class="mb-0"><span class="font-weight-bold">{{ profile_user.first_name }} {{ profile_user.last_name }}</span>
        </p>
        <p>{{ profile_user.email }}</p>
        {% if profile_user.age %}
            <p><span class="font-weight-bold">Age:</span> {{ profile_user.age }}</p>
        {% endif %}
        <p><span class="font-weight-bold">Joined:</span> {{ profile_user.date_joined }}</p>
        <p><span class="font-weight-bold">Last login:</span> {{ profile_user.last_login }}</p>
        {% if profile_user.about %}
            <p><span class="font-weight-bold">About:</span> {{ profile_user.about }}</p>
        {% endif %}
    </div>
    {% if profile_user == user %}
        <div class="card-footer">
            <a class="btn btn-secondary d-block mx-auto" href="{% url 'edit_profile' pk=profile_user.id %}">Edit
                profile</a>
        </div>
    {% endif %}
</div>

templates/users/profile_detail.html
{% extends 'base.html' %}

{% block title %}Posts{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col-12 col-md-4">
            {#        <h3 class="display-4 mb-3">{{ profile_user.username }}'s profile</h3>#}
            {% include 'users/_user_profile_partial.html' %}
        </div>
        <div class="col-12 col-md-8">
            <h3 class="display-4 mb-3">{{ profile_user.username }}'s posts</h3>
            {% include 'posts/_post_list_partial.html' %}
        </div>
    </div>
{% endblock content %}

templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>Edit profile</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Save</button>
    </form>
{% endblock content %}